### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by hshq** [karlseguin/blog#25]
I think the example about std.json.stringifyAlloc should free `json`:

`defer allocator.free(json);`

**Comment by karlseguin** [comment]
I added that line, but also added a comment pointing out that we can instead rely on the above call to `fa.reset()`

**Comment by hshq** [comment]
Sorry, I didn't notice `fa.reset()`.
Let’s talk about how this happened: I changed to use `std.testing.allocator` to test, and the result showed a memory leak.
Looking back now, I was faced with test code and there was a memory leak, but the calling method of `FixedBufferAllocator` was different and the usage pattern was different.
Therefore, it seems that `std.testing.allocator` is only suitable for testing the one-to-one allocation and release mode, and is not suitable for multiple allocation and one release mode?

**Comment by karlseguin** [comment]
Not sure I follow your conclusion. 

What I can say is that when you write code that takes an `std.mem.Allocator` parameter:

The first is that you treat the `allocator` argument like a black box. You don't make any assumption about whether it's a FixedBufferAllocator, an ArenaAllocator, a GeneralPurposeAllocator or anything else. This is the most common and safest approach. It means that you have to free any allocations you make (either in the same function or in some other function (e.g. deinit) that you expect your caller to call at some point in the future).  It's possible that your caller passed you an Arena or FixedBuffer based allocator, in which case your `deinit` is probably doing nothing. But since you make no assumptions, you dutifully clean up after youself.


The other case is that, while you're given an `std.mem.Allocator`, you **know** what the underlying implementation is and act accordingly (i.e. you don't free individual allocations you make, because you know it's an Arena and it'll be freed for you).

It's common to mix these two patterns.  For example, you might have a function that takes an `std.mem.Allocator` and create and uses an `Arena` from it:

```
parse(allocator: Allocator, input: []const u8) !Something {
  var arena = std.heap.ArenaAllocator.init(allocator);
  defer arena.deinit();
  return parseInternal(arena.allocator(), input)
}
```

The above code works no matter what the underlying allocator is that gets passed to `parse`, while providing the convenience of an Arena.

What does all this have to do with testing? Well, if you're testing a function that was written expecting an Allocator from a FixedBufferAllocator, then your test has to use a FixedBufferAllocator.  

Or, put differently, `std.testing.allocator` is suitable in cases where the code under test is written without any assumptions about what type of allocator it gets. This is, by far, the most common case. In a public API, this is almost always the case.

**Comment by hshq** [comment]
Thank you very much for your answer.
What you emphasized again here shows that the previous modifications to the code are to follow the principles of using allocators, even if these codes have no actual effect.
I understand, when facing the `std.mem.Allocator` parameter passed in, don’t make too many assumptions, just follow the usage pattern shown by its method.
While I was following your Zig tutorial, I typed the code by hand to enhance my Zig experience. This requires a bit more thought than copy/paste, so some code needs to be tweaked for testing.
Returning to this example, it does not involve passing `std.mem.Allocator` to other functions. When I typed this code, I was facing `FixedBufferAllocator`, so I switched to `std.testing.allocator` here for testing. I found that I had to comment out all method calls that did not exist in `std.mem.Allocator`. For example `defer fa.reset()`. This is the reality explained in the last paragraph of your comment this time, and the question in the last paragraph of my previous comment has a similar meaning.
I think I got a positive answer, so let me say one more thing, `ArenaAllocator` and so on reflect different usage patterns and provide different methods. When I face them directly, if there is a `std.testing.XXX` that provides the same methods, Wouldn't it be better to replace them painlessly with .allocator` for testing purposes?
I was expecting the test allocator to directly provide `reset()` / `deinit()` and other methods, but now I have some more thoughts. I want to just pass in `std.testing.allocator` when creating `ArenaAllocator`; similarly, `FixedBufferAllocator` does not need to be tested, and the tests related to it should be for the buffer itself passed to it.
