### ISSUE TITLE
'Language overview Part 1: .$field = $value

### ISSUE THREAD

**Issue by RikRoos** [karlseguin/blog#29]
In the section 'Language overview Part 1' I read:

"If you're like me and not a C++ programmer, the syntax to initalize fields, .$field = $value, might be a little odd, but you'll get used to it in no time."

I cannot spot any reference of .$field = $value in the learning text.  Or does this remark references to C++ syntax style?

**Comment by karlseguin** [comment]
The example directly above has:

```zig
return User{
  .name = name,
  .power = power,
};
```

the `.name = name` is what `.$field = $value` refers to.  I could drop the dollar sign, not sure if that would make it more or less clear. I'm afraid that if I just used `.field = value`, then some would interpret it as a literal  'field' and a literal 'value'. With the dollar sign, the hope is to indicate a pattern rather than a literal.
